name: Run CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  ci-build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        include:
          # 8.1 configurations
          - php-version: 8.1
            use-lowest-dependencies: true
            shared-test-version: 5.x-dev
          - php-version: 8.1
            use-lowest-dependencies: true
            shared-test-version: dev-main

          # 8.2 configurations
          - php-version: 8.2
            use-lowest-dependencies: false
            shared-test-version: 5.x-dev
          - php-version: 8.2
            use-lowest-dependencies: false
            shared-test-version: dev-main

          # 8.3 configurations
          - php-version: 8.3
            use-lowest-dependencies: false
            shared-test-version: 5.x-dev
          - php-version: 8.3
            use-lowest-dependencies: false
            shared-test-version: dev-main

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: ./.github/actions/ci
        with:
          php-version: ${{ matrix.php-version }}
          use-lowest-dependencies: ${{ matrix.use-lowest-dependencies }}
          shared-test-version: ${{ matrix.shared-test-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
